---
# This task installs and enables apache on webservers
- name: ensure apache is installed
  yum: pkg=httpd state=latest use_backend=yum3
- name: Start service httpd, if not started
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
- name: copy files to document root
  copy: src=cloud.png dest=/var/www/html/cloud.png
- name: copy application code to document root
  template: src=index.html.j2 dest=/var/www/html/index.html
  notify: restart apache
